name: JetsMinions-Fixer
author: [Geik, aisnhappy, Mehmet27]
main: xyz.geik.minion.fixer.Main
version: 1.0.1
api-version: 1.13
depend: [JetsMinions]
softdepend: [ASkyBlock, SuperiorSkyblock, FabledSkyBlock]
commands:
   miniongeik:
      description: remove area limit
